Search.appendIndex(
    [
                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix",
            "name": "Bitpix",
            "summary": "Valid\u0020BITPIX\u0020values",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#method_type"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#method_toString"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AUint8",
            "name": "Uint8",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Uint8"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AUint16",
            "name": "Uint16",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Uint16"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AUint32",
            "name": "Uint32",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Uint32"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AUint64",
            "name": "Uint64",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Uint64"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AFloat32",
            "name": "Float32",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Float32"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Bitpix\u003A\u003AFloat64",
            "name": "Float64",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Bitpix.html#enumcase_Float64"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel",
            "name": "Channel",
            "summary": "RGB\u0020image\u0020channels",
            "url": "classes/Dumbastro-FitsPhp-Channel.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel\u003A\u003AR",
            "name": "R",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Channel.html#enumcase_R"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel\u003A\u003AG",
            "name": "G",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Channel.html#enumcase_G"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel\u003A\u003AB",
            "name": "B",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Channel.html#enumcase_B"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel\u003A\u003AL",
            "name": "L",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Channel.html#enumcase_L"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Channel\u003A\u003AM",
            "name": "M",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Channel.html#enumcase_M"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Exceptions\\InvalidBitpixValue",
            "name": "InvalidBitpixValue",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Exceptions-InvalidBitpixValue.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Exceptions\\InvalidBitpixValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Exceptions-InvalidBitpixValue.html#method___construct"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Exceptions\\InvalidFits",
            "name": "InvalidFits",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Exceptions-InvalidFits.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Exceptions\\InvalidPath",
            "name": "InvalidPath",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Exceptions-InvalidPath.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits",
            "name": "Fits",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020a\u0020Fits\u0020object",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method___construct"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020the\u0020given\u0020FITS\u0020file\u0020based\u0020on\u0020block\u0020sizes",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_validate"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003AextractHeader\u0028\u0029",
            "name": "extractHeader",
            "summary": "Extract\u0020the\u0020FITS\u0020header\u0020block\u0020as\u0020a\u0020string",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_extractHeader"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003AextractImageBlob\u0028\u0029",
            "name": "extractImageBlob",
            "summary": "Extract\u0020the\u0020FITS\u0020image\u0020blob\u0020as\u0020a\u0020string\u003B\nit\u0020uses\u0020the\u0020NAXIS1\u0020and\u0020NAXIS2\u0020keywords\nto\u0020compute\u0020the\u0020length\u0020of\u0020the\u0020main\u0020data\u0020table",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_extractImageBlob"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003AsaveToPNG\u0028\u0029",
            "name": "saveToPNG",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_saveToPNG"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003AsaveToJPG\u0028\u0029",
            "name": "saveToJPG",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_saveToJPG"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003AsaveToTIFF\u0028\u0029",
            "name": "saveToTIFF",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_saveToTIFF"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#method_save"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024contents",
            "name": "contents",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_contents"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_path"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024fitsHeader",
            "name": "fitsHeader",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_fitsHeader"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_size"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024headerBlock",
            "name": "headerBlock",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_headerBlock"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024imageBlob",
            "name": "imageBlob",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_imageBlob"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Fits\u003A\u003A\u0024vipsImage",
            "name": "vipsImage",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Fits.html#property_vipsImage"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader",
            "name": "FitsHeader",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method___construct"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003AreadKeywords\u0028\u0029",
            "name": "readKeywords",
            "summary": "Initialize\u0020the\u0020keyword\u0020records\u0020array",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method_readKeywords"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "Return\u0020the\u0020FITS\u0020header\u0020as\u0020a\u0020string\u0020\u0028byte\u0020stream\u0029",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method_toString"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003AgetKeywordRecord\u0028\u0029",
            "name": "getKeywordRecord",
            "summary": "Retrieve\u0020a\u0020Keyword\u0020record\u0020based\u0020on\u0020key\u0020name",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method_getKeywordRecord"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003AgetKeywordValue\u0028\u0029",
            "name": "getKeywordValue",
            "summary": "Note\u003A\u0020the\u0020keyword\u0020key\u0020string\u0020is\u0020case\u002Dsensitive",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method_getKeywordValue"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "Check\u0020if\u0020header\u0020contains\u0020a\u0020multiple\u0020of\u002036\u0020records\n\u0028aka\u0020\u0027card\u0020images\u0027\u0029",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#method_isValid"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003A\u0024headerBlock",
            "name": "headerBlock",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#property_headerBlock"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003A\u0024keywords",
            "name": "keywords",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#property_keywords"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\FitsHeader\u003A\u003A\u0024blanks",
            "name": "blanks",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-FitsHeader.html#property_blanks"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob",
            "name": "ImageBlob",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method___construct"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003Apixels\u0028\u0029",
            "name": "pixels",
            "summary": "Returns\u0020a\u0020generator\u0020that\u0020yields\u0020image\u0020data\npixel\u0020by\u0020pixel",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_pixels"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003ApixelsMono\u0028\u0029",
            "name": "pixelsMono",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_pixelsMono"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003AdataBytes\u0028\u0029",
            "name": "dataBytes",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_dataBytes"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003AtoGdImage\u0028\u0029",
            "name": "toGdImage",
            "summary": "Convert\u0020to\u0020GD\u0020image",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_toGdImage"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003AgdPixel\u0028\u0029",
            "name": "gdPixel",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_gdPixel"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003AcreateGdImage\u0028\u0029",
            "name": "createGdImage",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_createGdImage"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003AtoSVG\u0028\u0029",
            "name": "toSVG",
            "summary": "Convert\u0020to\u0020SVG\u0020for\u0020display",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#method_toSVG"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024blob",
            "name": "blob",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_blob"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024header",
            "name": "header",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_header"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024bitpix",
            "name": "bitpix",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_bitpix"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024dataBits",
            "name": "dataBits",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_dataBits"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_width"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_height"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024naxis3",
            "name": "naxis3",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_naxis3"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\ImageBlob\u003A\u003A\u0024isColor",
            "name": "isColor",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-ImageBlob.html#property_isColor"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword",
            "name": "Keyword",
            "summary": "A\u0020FITS\u0020keyword\u0020record",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html#method___construct"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html#method_toString"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html#property_name"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html#property_value"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Keyword\u003A\u003A\u0024comment",
            "name": "comment",
            "summary": "",
            "url": "classes/Dumbastro-FitsPhp-Keyword.html#property_comment"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp",
            "name": "FitsPhp",
            "summary": "",
            "url": "namespaces/dumbastro-fitsphp.html"
        },                {
            "fqsen": "\\Dumbastro",
            "name": "Dumbastro",
            "summary": "",
            "url": "namespaces/dumbastro.html"
        },                {
            "fqsen": "\\Dumbastro\\FitsPhp\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/dumbastro-fitsphp-exceptions.html"
        }            ]
);
